//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DataAnnotations() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookStore.Resources.DataAnnotations", typeof(DataAnnotations).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Đã bán.
        /// </summary>
        public static string DaBan {
            get {
                return ResourceManager.GetString("DaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Giá bán lẽ.
        /// </summary>
        public static string GiaBanLe {
            get {
                return ResourceManager.GetString("GiaBanLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Giá bán sĩ.
        /// </summary>
        public static string GiaBanSi {
            get {
                return ResourceManager.GetString("GiaBanSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Giá khởi tạo.
        /// </summary>
        public static string GiaKhoiTao {
            get {
                return ResourceManager.GetString("GiaKhoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Giá nhập.
        /// </summary>
        public static string GiaNhap {
            get {
                return ResourceManager.GetString("GiaNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string GiaTri {
            get {
                return ResourceManager.GetString("GiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Loại hàng hóa.
        /// </summary>
        public static string LoaiHangHoa {
            get {
                return ResourceManager.GetString("LoaiHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ngày lập.
        /// </summary>
        public static string NgayLap {
            get {
                return ResourceManager.GetString("NgayLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string NhaCungCap {
            get {
                return ResourceManager.GetString("NhaCungCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nhãn hiệu.
        /// </summary>
        public static string NhanHieu {
            get {
                return ResourceManager.GetString("NhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tên hàng hóa.
        /// </summary>
        public static string TenHangHoa {
            get {
                return ResourceManager.GetString("TenHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tên loại hàng hóa.
        /// </summary>
        public static string TenLoaiHangHoa {
            get {
                return ResourceManager.GetString("TenLoaiHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tên nhà cung cấp.
        /// </summary>
        public static string TenNhaCungCap {
            get {
                return ResourceManager.GetString("TenNhaCungCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tên nhãn hiệu.
        /// </summary>
        public static string TenNhanHieu {
            get {
                return ResourceManager.GetString("TenNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Thuộc tính.
        /// </summary>
        public static string ThuocTinh {
            get {
                return ResourceManager.GetString("ThuocTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tồn kho.
        /// </summary>
        public static string TonKho {
            get {
                return ResourceManager.GetString("TonKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string TrangThai {
            get {
                return ResourceManager.GetString("TrangThai", resourceCulture);
            }
        }
    }
}
